### ISSUE TITLE
Launch event, including screening on Nijmegen Campus of documentary "Paywall" 

### ISSUE THREAD

**Issue by Frederik-D-Weber** [Radboud-University/osc-nijmegen#3]
Movie Screening of Movie "Paywall" https://paywallthemovie.com/screenings

When: 24th of October (like in many other places, possibly coordinate)
Where: Nijmegen Campus 
Who: Our community and people to join
Purpose: Attract and get people in the loop of local Projects and how we can organize

Proposed Event Schedule:
- Introduce community
- Watch Movie
- Discussion of Movie and how to establish what a local community could do in Nijmegen

Actions:
- [x] 1. Contact the Movie people
- [x] 1.1 Response
- [ ] 2. Get a good space for screening on the campus (e.g. https://www.ru.nl/cultuuropdecampus/)
- [ ] 3. Advertise the event
- [ ] 4. Prepare suggestion/presentation do direct Discussion at the Event
- [ ] 5. Prepare event

**Comment by Frederik-D-Weber** [comment]
contacted over website, waiting for response

**Comment by KristijanArmeni** [comment]
I just wrote to Cultuuropdecampus for a hall to screen the movie. We can expect response after Aug 31. Will report back.

**Comment by KristijanArmeni** [comment]
@Frederik-D-Weber @eirini-zormpa I got the reply by Cultuur op de campus. There is hall C (next to Sports Centre), which requires [fees](https://www.ru.nl/currentstudents/besides-your-study/student-life/theatre-hall/reservations/) (they said we could ask for exception). Then there are halls CC3 and CC2 in the Collegenzalencomplex. These two are quite big lecture halls (I've seen some screenings there and was OK) and next to Cultuurcafee . Imporantly, these two are free of charge.

I can go ahead and ask for CC2/CC3. But we'd need to settle the dates first. I think it should not be too close because we'd want some following first ... Any opinions?

**Comment by KristijanArmeni** [comment]
@Frederik-D-Weber I would even think mid November is too soon given that we haven't gather much following yet (say to have some ~50 folks on the list or so). We can start advertising these days and see how it builds. Or just place the date and hope for the best. I think all of the halls above are slightly oversized, but they are good spots on the campus.

@eirini-zormpa will inquire with whether whether C would be available for us (for free).

**Comment by KristijanArmeni** [comment]
@all-contributors add @johalgermissen for eventOrganizing,blog

**Comment by KristijanArmeni** [comment]
@all-contributors add @johalgermissen for eventOrganizing, blog
